Data as the factor premium and solve for the factor exposure
- Economic (e.g., unemployment rate) and market factors (e.g., CAPM)
- Fundamental indicators like the return on the zero-investment portfolio (e.g., SMB and HML in Fama French)
    
Data as the factor exposure and solve for the factor premium
- Technical indicators
- Fundamental factors, e.g., P/E
- Statistical factors
    - PCA from covariance of returns data: Principal components can be referred to as "factor premiums" because they can be thought of as representing systematic risk factors that drive the returns across all the assets (in the dataset) and thus could command a premium. However, the associated loadings are factor exposures.

In [1]:
import numpy as np
import pandas as pd
import yfinance as yf

In [2]:
watchlist = ['ARES', 'SNOW', 'NVDA', 'EMXC', 'FI', 'SPLK','PLTR',
             'CI', 'SOXL', 'TSLA', 'HD', 'WMT', 'QCOM', 'META']
start_date = '2022-11-01'
concatenated_data = pd.DataFrame()

for ticker in watchlist:
    data = yf.download(ticker, start=start_date)
    multi_index = pd.MultiIndex.from_product([[ticker], data.columns])
    data.columns = multi_index
    concatenated_data = pd.concat([concatenated_data, data], axis=1)

concatenated_data = concatenated_data.swaplevel(axis=1).sort_index(axis=1)
concatenated_data

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


Adj Close                                                 \
                  ARES          CI       EMXC          FI          HD   
Date                                                                    
2022-11-01   74.949364  318.192047  45.110294  104.019997  286.312469   
2022-11-02   73.548080  314.022797  44.444927  100.559998  279.223846   
2022-11-03   73.903198  317.330811  44.628139   94.570000  272.231873   
2022-11-04   75.294884  315.265747  45.929958   94.320000  274.678558   
2022-11-07   76.398636  317.457977  45.997459   96.389999  280.713104   
...                ...         ...        ...         ...         ...   
2024-01-05  117.050003  313.589996  54.540001  132.570007  342.940002   
2024-01-08  118.949997  313.630005  54.990002  135.229996  347.929993   
2024-01-09  115.779999  312.869995  54.230000  135.100006  346.190002   
2024-01-10  118.669998  307.720001  54.119999  135.399994  356.799988   
2024-01-11  118.320000  307.390015  54.240002  136.389999  356.529999   

                                                                       ...  \
                  META        NVDA       PLTR        QCOM        SNOW  ...   
Date                                                                   ...   
2022-11-01   95.199997  135.335312   8.650000  113.548363  159.500000  ...   
2022-11-02   90.540001  132.097580   8.220000  108.874023  147.750000  ...   
2022-11-03   88.910004  134.116180   8.080000  100.531868  150.470001  ...   
2022-11-04   90.790001  141.461014   7.930000  103.251297  132.309998  ...   
2022-11-07   96.720001  142.910004   7.020000  106.541710  129.100006  ...   
...                ...         ...        ...         ...         ...  ...   
2024-01-05  351.950012  490.970001  15.980000  136.729996  189.119995  ...   
2024-01-08  358.660004  522.530029  16.670000  139.029999  196.350006  ...   
2024-01-09  357.429993  531.400024  16.389999  139.889999  196.899994  ...   
2024-01-10  370.470001  543.500000  16.790001  139.309998  197.399994  ...   
2024-01-11  369.670013  548.219971  16.680000  139.029999  195.619995  ...   

             Volume                                                     \
                 HD       META      NVDA      PLTR      QCOM      SNOW   
Date                                                                     
2022-11-01  3309100  110189600  43281700  29800000   5749100   3153100   
2022-11-02  4426400   71821100  67262800  36042600  13936300   6244000   
2022-11-03  4823900   60664000  50006500  36419500  24706100   5936000   
2022-11-04  4401600   55638100  61257600  64338900  11977900  10787700   
2022-11-07  3260200   81987300  41006100  99332800   7570800   5756400   
...             ...        ...       ...       ...       ...       ...   
2024-01-05  2664000   13920700  41456800  57628800   6826500   5266800   
2024-01-08  2736200   13890200  64251000  49090000   7729400   4562000   
2024-01-09  2338100   13463900  77310000  35794500   5856900   3153600   
2024-01-10  4109300   22117200  53379600  41254400   5652500   4179600   
2024-01-11  3530400   17185200  59502800  39482900   7368300   5006500   

                                                    
                 SOXL     SPLK       TSLA      WMT  
Date                                                
2022-11-01  108638200  1923700   62688800  4938100  
2022-11-02  174985600  1933200   63070300  5174000  
2022-11-03  135668700  2232000   56538800  3658800  
2022-11-04  173041700  3061200   98622200  4889800  
2022-11-07  105846700  1522100   93916500  3788000  
...               ...      ...        ...      ...  
2024-01-05   73790500  1352000   92379400  7235600  
2024-01-08   73206500  1515900   85166600  6893600  
2024-01-09   67616000  1236500   96705700  7774100  
2024-01-10   62528400  1112800   91628500  6707300  
2024-01-11   77147900  2045000  105398000  4782300  

[300 rows x 84 columns]

In [3]:
sum(concatenated_data.isna().all().tolist())

0

In [4]:
ret_data = np.log(concatenated_data['Adj Close']/concatenated_data['Adj Close'].shift(1)).dropna()
ret_data

ARES        CI      EMXC        FI        HD      META  \
Date                                                                     
2022-11-02 -0.018873 -0.013190 -0.014860 -0.033829 -0.025070 -0.050188   
2022-11-03  0.004817  0.010479  0.004114 -0.061414 -0.025360 -0.018167   
2022-11-04  0.018656 -0.006529  0.028753 -0.002647  0.008947  0.020924   
2022-11-07  0.014553  0.006930  0.001469  0.021709  0.021732  0.063271   
2022-11-08  0.005138  0.010336  0.011464  0.021451  0.002993 -0.002588   
...              ...       ...       ...       ...       ...       ...   
2024-01-05  0.004882  0.023783  0.003674 -0.003238  0.012766  0.013819   
2024-01-08  0.016102  0.000128  0.008217  0.019866  0.014446  0.018886   
2024-01-09 -0.027011 -0.002426 -0.013917 -0.000962 -0.005014 -0.003435   
2024-01-10  0.024655 -0.016597 -0.002030  0.002218  0.030188  0.035833   
2024-01-11 -0.002954 -0.001073  0.002215  0.007285 -0.000757 -0.002162   

                NVDA      PLTR      QCOM      SNOW      SOXL      SPLK  \
Date                                                                     
2022-11-02 -0.024215 -0.050989 -0.042037 -0.076522 -0.099274 -0.076348   
2022-11-03  0.015166 -0.017178 -0.079717  0.018242 -0.043404 -0.028409   
2022-11-04  0.053318 -0.018739  0.026691 -0.128616  0.130517 -0.035192   
2022-11-07  0.010191 -0.121890  0.031371 -0.024560  0.064608  0.021291   
2022-11-08  0.020829  0.026706  0.022011  0.000465  0.058721  0.019648   
...              ...       ...       ...       ...       ...       ...   
2024-01-05  0.022639 -0.016755  0.004104  0.028969  0.013590  0.000394   
2024-01-08  0.062299  0.042273  0.016682  0.037517  0.092044  0.000263   
2024-01-09  0.016833 -0.016939  0.006167  0.002797 -0.000352  0.000788   
2024-01-10  0.022515  0.024112 -0.004155  0.002536 -0.008836  0.000722   
2024-01-11  0.008647 -0.006573 -0.002012 -0.009058  0.010242  0.001573   

                TSLA       WMT  
Date                            
2022-11-02 -0.058011 -0.006656  
2022-11-03  0.001534 -0.000213  
2022-11-04 -0.037092  0.001775  
2022-11-07 -0.051377  0.010444  
2022-11-08 -0.029767  0.002384  
...              ...       ...  
2024-01-05 -0.001851 -0.006678  
2024-01-08  0.012387  0.009779  
2024-01-09 -0.023097  0.006676  
2024-01-10 -0.004351  0.012352  
2024-01-11 -0.029146 -0.001117  

[299 rows x 14 columns]

### Solve for the factor exposure (fitted) and its estimated variance
- Libraries are often used (e.g., statsmodels, which provide p-values), but let's try to do it "by hand"

In [5]:
factors = pd.read_csv('F-F_Research_Data_5_Factors_2x3_daily.csv')
factors

Date  Mkt-RF   SMB   HML   RMW   CMA     RF
0    20221102   -2.67 -0.87  1.61  0.21  1.05  0.014
1    20221103   -1.03  0.39  0.31 -0.13  0.06  0.014
2    20221104    1.16 -0.25  1.27  2.21  0.63  0.014
3    20221107    0.87 -0.34  0.61  1.06  0.94  0.014
4    20221108    0.50 -0.55 -0.36 -0.19  0.06  0.014
..        ...     ...   ...   ...   ...   ...    ...
266  20231124    0.11  0.62  0.19 -0.51  0.24  0.021
267  20231127   -0.23 -0.14 -0.08  0.12 -0.25  0.021
268  20231128    0.06 -0.30  0.05 -0.17  0.02  0.021
269  20231129    0.01  0.58  0.69 -0.78 -0.06  0.021
270  20231130    0.35 -0.41  0.01 -0.11  0.19  0.021

[271 rows x 7 columns]

In [6]:
factors = factors.to_numpy()
rf = factors[:,-1][:, np.newaxis]
factors = factors[:,1:-1]

ret_data = ret_data.to_numpy()
ret_data = ret_data[:factors.shape[0],:]
excess_ret = ret_data - rf/365

print(excess_ret.shape)
print(factors.shape)

(271, 14)
(271, 5)


In [7]:
mean_factors = np.mean(factors, axis=0)
cov = np.cov(excess_ret.T, factors.T)
stock_factor_cov = cov[:excess_ret.shape[1], excess_ret.shape[1]:] # the upper right is the stock-factor covariances
factor_var = np.diag(cov[excess_ret.shape[1]:, excess_ret.shape[1]:])

betas = stock_factor_cov / factor_var
mean_excess_ret = np.mean(excess_ret, axis=0)
alphas = mean_excess_ret - np.dot(betas, mean_factors)

In [8]:
mean_excess_ret

array([ 0.00141508, -0.00077231,  0.00049296,  0.00078961,  0.00028426,
        0.00450476,  0.00452522,  0.00305174,  0.00042185,  0.00054998,
        0.00337101,  0.00217774,  0.00014305,  0.00035339])

In [9]:
alphas

array([ 8.23304196e-04, -8.62856003e-04,  1.96799775e-04,  5.23338046e-04,
       -8.07873527e-05,  2.56727510e-03,  1.45892613e-03,  1.39378370e-03,
       -7.00675265e-04, -1.30463890e-03, -1.21352924e-03,  1.05808162e-03,
       -1.61140998e-03,  8.16053743e-05])

In [10]:
betas.shape

(14, 5)

The variance of the beta estimates is given by:

$$
\hat{V}(\hat{\beta}_i) = \hat{\sigma}_i^2 \left( \sum_{t=1}^{T} f_t f_t' \right)^{-1}
$$

where $\hat{\sigma}_i^2$ is the estimated variance of the residuals for stock $i$:

$$
\hat{\sigma}_i^2 = \frac{1}{T} \sum_{t=1}^{T} (r_{it} - \hat{\beta}_i' \hat{f})^2
$$

In [11]:
def calculate_variance_beta(f, beta, r):
    
    T = f.shape[0]
    num_stocks = beta.shape[0]
    num_factors = f.shape[1]

    sum_ff = np.zeros((num_factors, num_factors))
    for t in range(T):
        sum_ff += np.outer(f[t], f[t])
    inv_sum_ff = np.linalg.inv(sum_ff)
    
    residuals_variances = np.zeros(num_stocks)
    for i in range(num_stocks):
        residuals = r[:, i] - np.dot(f, beta[i, :])
        residuals_variances[i] = np.mean(residuals**2)

    beta_variances = np.zeros((num_stocks, num_factors, num_factors))
    for i in range(num_stocks):
        beta_variances[i] = residuals_variances[i] * inv_sum_ff

    return beta_variances # covariances of the beta estimates for stocks

beta_variances = calculate_variance_beta(factors, betas, excess_ret)
np.diag(beta_variances[0]) # variances for the first stock's betas

array([2.40531639e-06, 5.34720929e-06, 5.45139196e-06, 7.34452372e-06,
       1.33988173e-05])

### Solve for the factor premium (fitted) and its estimated variance
- again, "by hand"

In [12]:
vol_ratio = (concatenated_data['Volume']/concatenated_data['Volume'].shift(1)).dropna()
# not saying it's a legit indicator; serves as a placeholder to show the process
vol_ratio

ARES        CI      EMXC        FI        HD      META  \
Date                                                                     
2022-11-02  0.930373  1.278128  1.058105  1.187561  1.337645  0.651796   
2022-11-03  1.159686  1.325267  6.029906  1.141446  1.089802  0.844654   
2022-11-04  0.561583  0.768415  0.502306  0.857384  0.912457  0.917152   
2022-11-07  0.882014  0.702385  0.457417  0.675104  0.740685  1.473582   
2022-11-08  2.331445  0.861292  1.812295  0.946797  1.034231  0.635322   
...              ...       ...       ...       ...       ...       ...   
2024-01-05  0.864112  1.322805  0.418279  0.903388  0.729383  1.150481   
2024-01-08  0.832448  0.682457  1.908201  0.956568  1.027102  0.997809   
2024-01-09  2.077598  0.760781  0.914103  0.946688  0.854506  0.969309   
2024-01-10  0.896687  0.947511  1.195554  0.864899  1.757538  1.642704   
2024-01-11  0.791519  1.065208  1.452013  1.047837  0.859124  0.777006   

                NVDA      PLTR      QCOM      SNOW      SOXL      SPLK  \
Date                                                                     
2022-11-02  1.554070  1.209483  2.424084  1.980273  1.610719  1.004938   
2022-11-03  0.743450  1.010457  1.772788  0.950673  0.775314  1.154562   
2022-11-04  1.224993  1.766606  0.484815  1.817335  1.275473  1.371505   
2022-11-07  0.669404  1.543900  0.632064  0.533608  0.611683  0.497223   
2022-11-08  1.451716  0.567324  1.239446  0.961174  1.392328  0.974575   
...              ...       ...       ...       ...       ...       ...   
2024-01-05  1.352433  1.442967  1.008301  1.233356  0.982995  0.903925   
2024-01-08  1.549830  0.851831  1.132264  0.866181  0.992086  1.121228   
2024-01-09  1.203250  0.729161  0.757743  0.691276  0.923634  0.815687   
2024-01-10  0.690462  1.152535  0.965101  1.325342  0.924757  0.899960   
2024-01-11  1.114710  0.957059  1.303547  1.197842  1.233806  1.837707   

                TSLA       WMT  
Date                            
2022-11-02  1.006086  1.047771  
2022-11-03  0.896441  0.707151  
2022-11-04  1.744328  1.336449  
2022-11-07  0.952286  0.774674  
2022-11-08  1.371467  1.325977  
...              ...       ...  
2024-01-05  0.900127  1.125725  
2024-01-08  0.921922  0.952734  
2024-01-09  1.135489  1.127727  
2024-01-10  0.947498  0.862775  
2024-01-11  1.150275  0.712999  

[299 rows x 14 columns]

In [13]:
vol_ratio = vol_ratio.to_numpy()
vol_ratio = vol_ratio[:ret_data.shape[0],:]
vol_ratio.shape

(271, 14)

The OLS estimator of the factor premium $f$ is given by:

$$
\hat{f} = \left( \sum_{t=1}^{T} \sum_{i=1}^{N} (\beta_{it} - \bar{\beta})(\beta_{it} - \bar{\beta})' \right)^{-1}
\sum_{t=1}^{T} \sum_{i=1}^{N} (\beta_{it} - \bar{\beta})(r_{it} - \bar{r})
$$

where

$$
\bar{\beta} = \frac{1}{NT} \sum_{t=1}^{T} \sum_{i=1}^{N} \beta_{it}
$$

and

$$
\bar{r} = \frac{1}{NT} \sum_{t=1}^{T} \sum_{i=1}^{N} r_{it}
$$

In [14]:
def calculate_premium(b_it, r_it):
    
    b_bar_scalar = np.mean(b_it)
    r_bar_scalar = np.mean(r_it)
    b_dev = b_it-b_bar_scalar
    r_dev = r_it-r_bar_scalar

    sum_outer_b_dev = sum(np.outer(b_dev[t,:], b_dev[t,:]) for t in range(b_dev.shape[0]))
    sum_prod_b_r_dev = sum(b_dev[t,:] * r_dev[t,:] for t in range(b_dev.shape[0]))

    f_hat = np.linalg.inv(sum_outer_b_dev) @ sum_prod_b_r_dev
    return f_hat

def calculate_variance_resid(b_it, r_it, f_hat): 
    r_hat = np.dot(b_it, f_hat)
    r_hat = r_hat[:, np.newaxis]
    resid = r_it-r_hat
    resid_var = np.var(resid, axis=0, ddof=1)  # ddof=1 for sample variance
    return resid, resid_var

The variance of the estimator is given by the following, which assumes homoscedasticity:

$$
\hat{V}(\hat{f}) = \sigma^2 \left( \sum_{t=1}^{T} \sum_{i=1}^{N} (\beta_{it} - \bar{\beta})(\beta_{it} - \bar{\beta})' \right)^{-1}
$$

where

$$
\sigma^2 = \frac{1}{NT} \sum_{t=1}^{T} \sum_{i=1}^{N} (r_{it} - \beta_{it}'\hat{f})^2
$$


The variance of the estimator can also be calculated by the following, which accounts for the varying levels of risk associated with different assets:

$$
\hat{V}(\hat{f}) = \left( \sum_{t=1}^{T} \sum_{i=1}^{N} \beta_{it} \beta_{it}' \right)^{-1}
\left( \sum_{t=1}^{T} \sum_{i=1}^{N} \sigma_i^2 \beta_{it} \beta_{it}' \right)
\left( \sum_{t=1}^{T} \sum_{i=1}^{N} \beta_{it} \beta_{it}' \right)^{-1}
$$

In [15]:
def calculate_variance_f_hat(b_it, residuals):

    T, N = b_it.shape[0], b_it.shape[1]
    sum_beta_outer = np.zeros((N, N))
    for t in range(T):
        sum_beta_outer += np.outer(b_it[t], b_it[t])
    inv_sum_beta_outer = np.linalg.inv(sum_beta_outer)
    
    weighted_sum = np.zeros((N, N))
    for t in range(T):
        for i in range(N):
            weighted_sum += residual_variances[i] * np.outer(b_it[t], b_it[t])
    
    variance_f_hat = np.diag(inv_sum_beta_outer @ weighted_sum @ inv_sum_beta_outer)
    return variance_f_hat


f_hat = calculate_premium(vol_ratio, excess_ret)
residuals, residual_variances = calculate_variance_resid(vol_ratio, excess_ret, f_hat)

calculate_variance_f_hat(vol_ratio, residual_variances)

array([2.95825442e-04, 2.97152209e-04, 2.54800212e-05, 3.93047631e-04,
       5.97640043e-04, 4.76155495e-04, 9.81627144e-04, 4.38536899e-04,
       6.35074139e-04, 3.27414841e-04, 1.42644756e-03, 4.62347644e-05,
       1.24515836e-03, 5.37399173e-04])

When estimating f_hat, better to check for 1. outliers (MAD estimator of the factor premium could work better than OLS) and 2. heteroscedasticity (GLS estimator should be better).

Regarding the third bullet point - obtaining principal components is pretty straightforward.

References:<br>
https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html<br>
https://meketa.com/wp-content/uploads/2020/05/Factor-Exposure-Analysis.pdf<br>
Quantitative Equity Portfolio Management (2022) by Ludwig Chincarini and Daehwan Kim